server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://mysql-bank-statement:3309/statement_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
